### ISSUE TITLE
[Feature Request] Guide for New Students to Contribute to Open Source

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/BitCamp#65]
**Is your proposal related to a problem?**
Students new to programming aren't given the resources to contribute to the repo.

**Describe the solution you'd like**
Add guides that teach the fundamentals of open source.

**Comment by lazyplatypus** [comment]
How to open a pull request, open an issue, conduct a code review.

**Comment by MinyMeep1** [comment]
A guide on how to work with markdown. During my task, I wasn't sure what the three ### was and when I look through the edits via serverless I saw that ### meant heading 3.  Maybe if we had a markdown documentation students or open contributors would know how to properly use markdown.

**Comment by lazyplatypus** [comment]
@MinyMeep1 we are going to create a new document targeted at students who want to make their first PR into our repo. This will have a checklist of things they should do/know before they tackle a particular issue. 

For example, 
Knowing how
- PRs
- Github Issues
- Markdown
- Code Reviews
- Other aspects of Github
works is crucial to the success of the student. 

In addition, we should have more instructions on how they can start tackling a particular issue. For example, let's say that step 4 on a particular learning lab doesn't go enough in depth about a particular topic. Students should try the learning lab from step 1 all the way to step 4 before trying to fix the issue. 

Also, students should be encouraged to open issues for other issues they discover while they are working on their own task.

**Comment by shreythecray** [comment]
Make contributing more interesting, friendly and eye-catching. Maybe gamify it so we can have challenges for the number of PR's that students make and those who reach certain levels get badges or swag?

**Comment by lazyplatypus** [comment]
@shreythecray maybe we should add something like -> https://allcontributors.org/ to the repo?

**Comment by emsesc** [comment]
Emphasize the importance of contributing and how it helps students (I think @MinyMeep1 brought this up before)

**Comment by danzelo1** [comment]
I think the points @lazyplatypus made are really great and will help students a lot. Going off of that, I think it’s important that we make these resources quick and easy to access and follow by linking step-by-step instructions to the notion page associated with each BitCamp, or whatever page the code and homework’s will be linked on.

To encourage them to contribute, maybe we could try to get students to share their work every week. I’m not sure if this would be possible with the streaming platforms we’re using, but maybe we could get a student to explain the homework every week instead of the mentors going over it and those who volunteer will get some reward like @shreythecray said.

**Comment by MinyMeep1** [comment]
We need to as well include how to do "Gitignore"

**Comment by MinyMeep1** [comment]
I just wanted to get an opinion on it right now. I'm still fixing the kinks but this is what I have now and I'll be adding more sections like "What is a GitHub issue"
